---
- name: Manage SSH keys and users
  hosts: all
  become: true
  tasks:
    - name: Create a new user
      user:
        name: lareb
        state: present
        shell: /bin/bash
        create_home: yes

    - name: Add SSH key for the user
      authorized_key:
        user: lareb
        key: "{{ lookup('file', '/home/sakir/.ssh/id_rsa.pub') }}"
        state: present

    - name: Configure SSH access for the user
      lineinfile:
        dest: /etc/ssh/sshd_config
        line: "AllowUsers lareb"
        insertafter: "#PermitRootLogin yes"
        state: present
      notify:
        - restart sshd

  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
